"""Fan Zone Profit Engine — agent orchestration.

Runs the six-step reasoning pipeline for a given host city and returns the
structured decision consumed by POST /agent:

  1. get_upcoming_match(city)
  2. get_fan_spending_profiles([home_nationality, away_nationality])
  3. get_relevant_tenants(<categories the fans spend on>)
  4. revenue = (home_fans*home_spend + away_fans*away_spend) * 0.65
  5. build the action plan (tenant activations, staffing, campaigns, fraud level)
  6. log_agent_action(...)

The deterministic business logic lives here. The natural-language `reasoning`
narrative is generated by Vertex AI (Gemini 1.5 Pro) when GCP credentials are
available; otherwise a templated narrative is produced so the endpoint always
returns the full contract.
"""

import os

import tools

# Capture rate: fraction of fan daily spend the fan zone realistically captures.
CAPTURE_RATE = 0.65


class MatchNotFoundError(Exception):
    """Raised when no fixture exists for the requested city."""


def _fraud_level(profiles):
    """Derive an overall fraud level from the per-nationality fraud indices."""
    if not profiles:
        return "low", 0.0
    peak = max(p.get("fraud_risk_index", 0.0) for p in profiles)
    if peak >= 0.6:
        return "high", peak
    if peak >= 0.35:
        return "medium", peak
    return "low", peak


def _build_action_plan(match, profiles, tenants, fraud_level):
    """Turn the raw data into concrete tenant activations, staffing and campaigns."""
    activations = []
    # Map each fans' top spend category to the strongest tenant in that category.
    wanted = []
    for p in profiles:
        for cat in p.get("top_spend_categories", []):
            if cat not in wanted:
                wanted.append(cat)
    for cat in wanted:
        match_tenants = [t for t in tenants if t.get("category") == cat]
        for t in match_tenants:
            activations.append(
                {
                    "tenant": t["name"],
                    "category": cat,
                    "reason": (
                        f"High {cat} demand from inbound fans "
                        f"(avg ${_avg_spend_for_category(profiles, cat):.0f}/day)."
                    ),
                }
            )

    total_fans = match["home_fans"] + match["away_fans"]
    staffing = (
        f"Scale to ~{max(1, round(total_fans / 250))} fan-zone staff for "
        f"{total_fans:,} expected fans; double security if fraud level is high."
    )
    campaigns = [
        f"Geo-targeted push to {p['nationality']} fans featuring "
        f"{', '.join(p.get('top_spend_categories', [])[:2])}."
        for p in profiles
    ]
    return {
        "tenant_activations": activations,
        "staffing": staffing,
        "campaigns": campaigns,
        "fraud_level": fraud_level,
    }


def _avg_spend_for_category(profiles, category):
    relevant = [p for p in profiles if category in p.get("top_spend_categories", [])]
    if not relevant:
        return 0.0
    return sum(p.get("avg_daily_spend_usd", 0) for p in relevant) / len(relevant)


def _reasoning_narrative(match, profiles, revenue, fraud_level, action_plan):
    """Generate the chain-of-thought narrative via Vertex AI, with a fallback."""
    facts = {
        "fixture": match["fixture"],
        "city": match["city"],
        "home_fans": match["home_fans"],
        "away_fans": match["away_fans"],
        "revenue_projection_usd": revenue,
        "fraud_level": fraud_level,
        "tenant_activations": [a["tenant"] for a in action_plan["tenant_activations"]],
    }
    narrative = _vertex_reasoning(facts)
    if narrative:
        return narrative
    # Deterministic fallback so the endpoint always returns the full contract.
    tenants = ", ".join(facts["tenant_activations"]) or "no tenants"
    return (
        f"For {facts['fixture']} in {facts['city']}, an inbound wave of "
        f"{facts['home_fans'] + facts['away_fans']:,} fans is expected. "
        f"Applying a {CAPTURE_RATE:.0%} capture rate to blended fan spend yields a "
        f"${revenue:,.0f} projected fan-zone revenue. Recommended tenant "
        f"activations: {tenants}. Overall fraud risk is assessed as "
        f"{fraud_level}; staffing and security are sized accordingly."
    )


def _vertex_reasoning(facts):
    """Call Vertex AI Gemini for the narrative. Returns None if unavailable."""
    project = os.environ.get("GCP_PROJECT")
    region = os.environ.get("GCP_REGION", "us-central1")
    if not project:
        return None
    try:
        import vertexai
        from vertexai.generative_models import GenerativeModel

        vertexai.init(project=project, location=region)
        model = GenerativeModel(os.environ.get("GEMINI_MODEL", "gemini-1.5-pro"))
        prompt = (
            "You are the Fan Zone Profit Engine. In 3-4 sentences, explain the "
            "revenue and operations recommendation for this World Cup fan zone "
            "based on these facts. Be concrete and business-focused.\n\n"
            f"Facts: {facts}"
        )
        resp = model.generate_content(prompt)
        return (resp.text or "").strip() or None
    except Exception:
        # No credentials / SDK / network — fall back to the templated narrative.
        return None


def run_agent(city):
    """Run the full pipeline for `city` and return the POST /agent response dict."""
    # Step 1 — fixture.
    match = tools.get_upcoming_match(city)
    if not match:
        raise MatchNotFoundError(city)

    home_nat = match["home_team_nationality"]
    away_nat = match["away_team_nationality"]

    # Step 2 — fan spending profiles (home first, then away).
    profiles = tools.get_fan_spending_profiles([home_nat, away_nat])
    profile_by_nat = {p["nationality"]: p for p in profiles}
    home_spend = profile_by_nat.get(home_nat, {}).get("avg_daily_spend_usd", 0)
    away_spend = profile_by_nat.get(away_nat, {}).get("avg_daily_spend_usd", 0)

    # Step 3 — relevant tenants for the categories these fans spend on.
    categories = []
    for p in profiles:
        for cat in p.get("top_spend_categories", []):
            if cat not in categories:
                categories.append(cat)
    tenants = tools.get_relevant_tenants(categories)

    # Step 4 — revenue projection.
    home_component = match["home_fans"] * home_spend
    away_component = match["away_fans"] * away_spend
    revenue = (home_component + away_component) * CAPTURE_RATE

    # Step 5 — action plan + fraud assessment.
    fraud_level, fraud_peak = _fraud_level(profiles)
    action_plan = _build_action_plan(match, profiles, tenants, fraud_level)

    reasoning = _reasoning_narrative(match, profiles, revenue, fraud_level, action_plan)

    response = {
        "match_summary": {
            "fixture": match["fixture"],
            "city": match["city"],
            "venue": match["venue"],
            "date": match["date"],
            "home_team": match["home_team"],
            "away_team": match["away_team"],
        },
        "fan_wave": {
            "total_fans": match["home_fans"] + match["away_fans"],
            "home_fans": match["home_fans"],
            "away_fans": match["away_fans"],
            "nationalities": [
                {
                    "nationality": p["nationality"],
                    "count": match["home_fans"]
                    if p["nationality"] == home_nat
                    else match["away_fans"],
                    "avg_daily_spend_usd": p.get("avg_daily_spend_usd", 0),
                    "top_spend_categories": p.get("top_spend_categories", []),
                    "fraud_risk_index": p.get("fraud_risk_index", 0.0),
                }
                for p in profiles
            ],
        },
        "action_plan": action_plan,
        "revenue_projection": {
            "amount_usd": round(revenue, 2),
            "formula": "(home_fans*home_spend + away_fans*away_spend) * 0.65",
            "breakdown": {
                "home": round(home_component, 2),
                "away": round(away_component, 2),
                "capture_rate": CAPTURE_RATE,
            },
        },
        "fraud_alert": {
            "level": fraud_level,
            "message": (
                f"Peak fraud-risk index across inbound fan groups is "
                f"{fraud_peak:.2f}; risk classified as {fraud_level}."
            ),
        },
        "reasoning": reasoning,
    }

    # Step 6 — persist the decision.
    response["action_id"] = tools.log_agent_action(
        {
            "city": match["city"],
            "fixture": match["fixture"],
            "revenue_projection_usd": response["revenue_projection"]["amount_usd"],
            "fraud_level": fraud_level,
            "tenant_activations": [
                a["tenant"] for a in action_plan["tenant_activations"]
            ],
        }
    )

    return response
